spring.application.name=object-service
server.port=8082
spring.output.ansi.enabled=always

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

secret-key=${SECRET_KEY}

bucket.service.url=http://localhost:8081

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB